baseurl      = "https://piresh.at/"
title        = "Les Pires Hat"
languageCode = "en-en"
DefaultContentLanguage = "en"
theme        = "hello-friend-ng"
paginate     = 10

disableKinds = ["RSS"]

[params]
dateform        = "2 Jan 2006"
dateformShort   = "2 Janvier"
dateformNum     = "02/01/2006"
dateformNumTime = "02/01/2006 15:04"

# Subtitle for home
homeSubtitle = "On aura votre <strike>dra</strike>peau"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Metadata mostly used in document's head
description = "On aura votre (dra)peau"
keywords = "homepage, blog"
images = [""]

# Colors for favicons
#
[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"


[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[languages]
[language.en]
title = "Les Pires Hat"
subtitle = "On aura votre (dra)peau"
keywords = ""
copyright = 'Les Pires Hat'
readOtherPosts = "More content"

[params.logo]
logoText = "guest@piresh.at"
logoHomeLink = "/"

[params.portrait]
path = "https://i.ibb.co/qdFVw1n/logo.png"
alt = "Les Pires Hat logo"

# And you can even create generic menu
[menu]
[[menu.main]]
identifier = "blog"
name       = "Blog"
url        = "https://lespireshat.medium.com/"
weight = 1
[[menu.main]]
identifier = "team"
name       = "Team"
url        = "team"
weight = 2
[[menu.main]]
identifier = "ctfs"
name       = "CTFs"
url        = "ctfs"
weight = 3
[[menu.main]]
identifier = "sponsors"
name       = "Sponsors"
url        = "sponsors"
weight = 4
[[menu.main]]
identifier = "about"
name       = "About"
url        = "about"
weight = 5

# Social icons
[[params.social]]
name = "twitter"
url  = "https://twitter.com/LesPiresHat"

[[params.social]]
name = "github"
url  = "https://github.com/pireshat/"

[[params.social]]
name = "medium"
url  = "https://medium.com/@lespireshat"

[[params.social]]
name = "codechef"
url  = "https://ctftime.org/team/75893"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/company/les-pires-hat"